### ISSUE TITLE
Menu item is actually named ActivateToken 

### ISSUE THREAD

**Issue by studgeek** [CoatiSoftware/idea-sourcetrail#5]
FYI, In CLion the menu item is actually named "ActivateToken" rather than Send Location like the README and https://www.sourcetrail.com/documentation says.

Also, install steps are a bit off. They should be:
"Go to plugins and select Marketplace"

**Comment by studgeek** [comment]
I did pull request for #6 to fix install instructions.

For ActivateToken I assume you want to change that menu item in the code so I didn't update doc.

**Comment by mlangkabel** [comment]
Thank you very much for bringing this up and providing the pull request. It looks like both, the install steps and the name of the context menu action changed for later versions of intelliJ.

**Comment by mlangkabel** [comment]
Fixed with release 0.4.9. According to the JetBrains plugins page "The plugin has been submitted for moderation. The request will be processed within two business days."
