### ISSUE TITLE
"Send Location" should switch focus to SourceTrail application

### ISSUE THREAD

**Issue by ajdavis** [CoatiSoftware/idea-sourcetrail#9]
I think that executing the "Send Location" action in CLion (or other JetBrains IDE) should switch focus to the SourceTrail application and bring its window to the foreground. That's what I intuitively expected, and it would be convenient: whenever I execute "Send Location", the next step I want to take is to look at that location in SourceTrail.

**Comment by mlangkabel** [comment]
Thank you for bringing this up. As this is not only relevant for the IDEA plugin, but for every plugin, I have created an issue for this on the Sourcetrail issue tracker: https://github.com/CoatiSoftware/Sourcetrail/issues/785

Closing this now to prevent duplicate discussion
